apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-cvmfs-fix
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
data:
  cvmfs-fix.sh: |
    sleep 10;
    while [ "$(kubectl get pods -n {{ .Release.Namespace }} -l 'app=cvmfscis' -l 'component=nodeplugin' -o custom-columns=STATUS:.status.phase --no-headers)" != "Running" ]; do
      echo "Waiting on nodeplugin pod to enter 'Running' status.";
      sleep 1;
    done && \
    echo "Deleting nodeplugin pods..."
    kubectl get pods -n {{ .Release.Namespace }} -l 'app=cvmfscis' -l 'component=nodeplugin' -o name | xargs kubectl -n {{ .Release.Namespace }} delete && \
    echo "Deleted nodeplugin pods."
