apiVersion: v1
metadata:
  name: {{ include "galaxy.fullname" . }}-configs
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
{{- if .Values.useSecretConfigs }}
kind: Secret
type: Opaque
stringData:
{{- else }}
kind: ConfigMap
data:
{{- end }}
  {{- range $key, $entry := .Values.configs -}}
  {{- if $entry -}}
  {{- $key | nindent 2 -}}: |
  {{- $isYamlFile := (or (hasSuffix ".yml" $key)  (hasSuffix ".yaml" $key)) -}}
  {{- $original := (ternary (toYaml $entry) $entry $isYamlFile) -}}
  {{- $nowhitespace := (regexReplaceAll "{{\\s*([^}\\s]+)\\s*}}" $original "{{$1}}") -}}
  {{- tpl (tpl $nowhitespace $) $ | nindent 4 -}}
  {{- end -}}
  {{- end -}}
