{{ if .Values.cronJobs -}}
{{ range $key, $cronjob := .Values.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "galaxy.fullname" $ }}-maintenance-{{ $key }}
  labels:
    {{- include "galaxy.labels" $ | nindent 4 }}
spec:
  schedule: {{ $cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            {{- toYaml $cronjob.securityContext | nindent 12 }}
          {{- with $.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 16 }}
          {{- end }}
          containers:
          - name: galaxy-maintenance-{{ $key }}
            image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
            imagePullPolicy: {{ $.Values.image.pullPolicy }}
            # delete all tmp files older than walltime limit
            command: {{ $cronjob.command }}
            {{- if $cronjob.args }}
            args:
              {{- range $arg := $cronjob.args }}
              - {{ tpl $arg $ }}
              {{- end }}
            {{- end }}
            volumeMounts:
            - name: galaxy-data
              mountPath: {{ $.Values.persistence.mountPath }}
          volumes:
          - name: galaxy-data
            {{- if $.Values.persistence.enabled }}
            persistentVolumeClaim:
              claimName: {{ template "galaxy.pvcname" $ }}
            {{- else }}
            emptyDir: {}
            {{- end }}
          restartPolicy: OnFailure
{{- end }}
{{- end }}
