{{ range $key, $cronjob := .Values.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "galaxy.fullname" $ }}-cron-{{ $key }}
  labels:
    {{- include "galaxy.labels" $ | nindent 4 }}
spec:
  schedule: {{ $cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- if $cronjob.securityContext }}
          securityContext:
            {{- toYaml $cronjob.securityContext | nindent 12 }}
          {{- end}}
          {{- if $cronjob.nodeSelector }}
          nodeSelector:
            {{- toYaml $cronjob.nodeSelector | nindent 12 }}
          {{- else if $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml $.Values.nodeSelector | nindent 12 }}
          {{- end }}
          containers:
          - name: galaxy-cron-{{ $key }}
            image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
            imagePullPolicy: {{ $.Values.image.pullPolicy }}
            command:
            {{- range $cmd := $cronjob.command }}
              - {{ tpl $cmd $ | quote }}
            {{- end}}
            {{- if $cronjob.args }}
            args:
              {{- range $arg := $cronjob.args }}
              - {{ tpl $arg $ | quote }}
              {{- end }}
            {{- end }}
            volumeMounts:
            - name: galaxy-data
              mountPath: {{ $.Values.persistence.mountPath }}
            {{- range $key, $entry := $cronjob.extraFileMappings -}}
            - name: {{ include "galaxy.getExtraFilesUniqueName" $key }}
              mountPath: {{ $key }}
              subPath: {{ include "galaxy.getFilenameFromPath" $key }}
            {{- end }}
          volumes:
          - name: galaxy-data
            {{- if $.Values.persistence.enabled }}
            persistentVolumeClaim:
              claimName: {{ template "galaxy.pvcname" $ }}
            {{- else }}
            emptyDir: {}
            {{- end }}
        {{- range $key, $entry := $cronjob.extraFileMappings -}}
        - name: {{ include "galaxy.getExtraFilesUniqueName" $key }}
          {{- if $entry.useSecret }}
          secret:
            secretName: {{ printf "%s-%s" (include "galaxy.fullname" $) (include "galaxy.getExtraFilesUniqueName" $key) }}
          {{- else }}
          configMap:
            name: {{ printf "%s-%s" (include "galaxy.fullname" $) (include "galaxy.getExtraFilesUniqueName" $key) }}
          {{- end }}
        {{- end }}
          restartPolicy: OnFailure
{{- end }}
