{{- if and .Values.jobs.priorityClass.enabled (not .Values.jobs.priorityClass.existingClass) }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "galaxy.pod-priority-class" . }}
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
value: {{ if .Values.jobs.priorityClass.value -}} 
       {{ .Values.jobs.priorityClass.value}} 
       {{- else -}} 
       -1000 
       {{- end}}
preemptionPolicy: Never
globalDefault: false
description: "Galaxy jobs will not preempt existing workloads and depending on the value spin up new resources for the computation."
{{ end }}
