{{- if and .Values.jobs.priorityClass.enabled (not .Values.jobs.priorityClass.existingClass) }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "galaxy.pod-priority-class" . }}
  labels:
    {{- include "galaxy.labels" . | nindent 4 }}
value: {{ if .Values.jobs.priorityClass.value -}} 
       {{ .Values.jobs.priorityClass.value}} 
       {{- else -}} 
       -1000 
       {{- end}}
preemptionPolicy: Never
globalDefault: false
description: "By default, Galaxy jobs will not preempt existing workloads but will run when cluster resources are available. Depending on the cluster setup, the preemption value can be modified to prompt scaling of the cluster for the computation."
{{ end }}
