{{- if .Values.refdata.enabled }}
{{- range $key, $entry := .Values.refdata.galaxyPersistentVolumeClaims -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "galaxy.fullname" $ }}-refdata-gxy-{{ $key }}-pvc
  labels:
    {{- include "galaxy.labels" $ | nindent 4 }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: {{ $entry.storage }}
  storageClassName: {{ $entry.storageClassName }}
---
{{- end }}
{{- end }}
