name: Package
on:
  pull_request_target:
    types: [closed]
  workflow_dispatch:
    inputs:
      manual-package-invocation:
        description: 'Package (y/n)?'
        required: true
        default: 'y'
jobs:
  package:
    if: github.event.pull_request.merged == true || github.event.inputs.manual-package-invocation == 'y'
    name: Package and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
           persist-credentials: false
      - uses: cloudve/helm-ci@master
        with:
          chart-name: galaxy
          charts-repo: cloudve/helm-charts
          github-token: ${{ secrets.CHARTS_TOKEN }}
          charts-token: ${{ secrets.CHARTS_TOKEN }}
          github-labels: ${{ join(github.event.pull_request.labels.*.name, ', ') }}
          git-branch: ${{ github.event.pull_request.base.ref }}
